---
# Runs a command (or sequence of commands) and prints the output
# Connection type:
# - SSH
# Command:
#   ansible-playbook -i hosts ros-cmd-output.yml
#
- name: RouterOS test with network_cli connection
  hosts: routers
  gather_facts: false
  tasks:
    - name: Run a command
      community.routeros.command:
        commands:
          - /system resource print
      register: system_resource_print
    - name: Print its output
      ansible.builtin.debug:
        var: system_resource_print.stdout_lines
