---
# Self contained playbook (no separate inventory or variables required).
# This sets /radius/incoming/accept to 'yes' in an indemponent way.
# Fetches IP addresses from the router and prints the first one.
# 
# Connection type:
# - API
# Command:
#   ansible-playbook ros-single.yml
#
- name: RouterOS test with API
  hosts: localhost
  gather_facts: false
  vars:
    ansible_host: 192.168.1.12
    username: hal9000
    password: password123
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      password: "{{ password }}"
      username: "{{ username }}"
      tls: false
      force_no_cert: false
      validate_certs: false
      validate_cert_hostname: false
      ca_path: /path/to/ca-certificate.pem
  tasks:
    - name: Change RADIUS incoming to active.
      community.routeros.api_modify:
        path: radius incoming
        data:
          - accept: yes

    - name: Retrieve facts
      community.routeros.api_facts:
    - ansible.builtin.debug:
        msg: "First IP address: {{ ansible_net_all_ipv4_addresses[0] }}"
